# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_attr"
version = "1.1.3"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description= "ANSI control escape sequences using an XML-like syntax for attributes like color on video displays and emulators"
categories = ["ANSI escape sequences"]
keywords = ["fortran", "terminal control sequences", "escape sequences", "in-band terminal control" ]
homepage = "https://github.com/urbanjost/M_attr.git"

[build]
external-modules = ["ifport", "dfport"]

[install]
library=true

[[executable]]
name="tat"
source-dir="app"
main="tat.f90"
[executable.dependencies]
M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }

[[executable]]
name="redirect"
source-dir="app"
main="redirect.F90"

[[executable]]
name="plain"
source-dir="app"
main="plain.f90"

[[executable]]
name="light"
source-dir="app"
main="light.f90"

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_attr.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
