M_attr: m_attr Module Reference
m_attr Module Reference
Data Types
interface advice
interface attr
interface str
Functions/Subroutines
character(len=:) function, allocatable, private attr_scalar (string, reset)
character(len=:) function, dimension(:), allocatable, private attr_matrix (strings, reset, chars)
subroutine kludge_bug (strings, reset, chars, expanded)
character(len=:) function, allocatable, private attr_scalar_width (string, reset, chars)
subroutine, private vt102 ()
subroutine, public attr_mode (manner)
!>
subroutine, private wipe_dictionary ()
subroutine, public attr_update (key, valin, mono_valin)
!>
character(len=:) function, allocatable, private get (key)
subroutine, private locate (list, value, place, ier, errmsg)
subroutine, private remove (list, place)
subroutine, private replace (list, value, place)
subroutine, private insert (list, value, place)
subroutine, public alert (type, message, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, ga, gb, gc, gd, ge, gf, gg, gh, gi, gj)
!>
character(len=:) function, allocatable msg_scalar (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, generica, genericb, genericc, genericd, generice, genericf, genericg, generich, generici, genericj, sep)
character(len=:) function, allocatable msg_one (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, generica, genericb, genericc, genericd, generice, genericf, genericg, generich, generici, genericj, sep)
Variables
character(len=:), dimension(:), allocatable, save keywords
character(len=:), dimension(:), allocatable, save values
character(len=:), dimension(:), allocatable, save mono_values
character(len=:), allocatable, save mode
character(len= *), parameter nl =new_line('a')
character(len= *), parameter nul =achar(0)
character(len= *), parameter bel =achar(7)
character(len= *), parameter bs =achar(8)
character(len= *), parameter ht =achar(9)
character(len= *), parameter lf =achar(10)
character(len= *), parameter vt =achar(11)
character(len= *), parameter ff =achar(12)
character(len= *), parameter cr =achar(13)
character(len= *), parameter so =achar(14)
character(len= *), parameter si =achar(15)
character(len= *), parameter can =achar(24)
character(len= *), parameter sub =achar(26)
character(len= *), parameter esc =achar(27)
character(len= *), parameter del =achar(127)
character(len= *), parameter code_start =esc//'['
character(len= *), parameter code_end ='m'
character(len= *), parameter code_reset =CODE_START//'0'//CODE_END
character(len= *), parameter clear_display =CODE_START//'2J'
character(len= *), parameter home_display =CODE_START//'H'
character(len= *), parameter bell =achar(7)
character(len= *), parameter at_bold ='1'
character(len= *), parameter at_italic ='3'
character(len= *), parameter at_underline ='4'
character(len= *), parameter at_inverse ='7'
character(len= *), parameter black ='0'
character(len= *), parameter red ='1'
character(len= *), parameter green ='2'
character(len= *), parameter yellow ='3'
character(len= *), parameter blue ='4'
character(len= *), parameter magenta ='5'
character(len= *), parameter cyan ='6'
character(len= *), parameter white ='7'
character(len= *), parameter default ='9'
character(len= *), parameter fg ='3'
character(len= *), parameter bg ='4'
character(len= *), parameter fg_intense ='9'
character(len= *), parameter bg_intense ='10'
character(len= *), parameter on =''
character(len= *), parameter off ='2'
character(len= *), parameter, public fg_red = CODE_START//FG//RED//CODE_END
character(len= *), parameter, public fg_cyan = CODE_START//FG//CYAN//CODE_END
character(len= *), parameter, public fg_magenta = CODE_START//FG//MAGENTA//CODE_END
character(len= *), parameter, public fg_blue = CODE_START//FG//BLUE//CODE_END
character(len= *), parameter, public fg_green = CODE_START//FG//GREEN//CODE_END
character(len= *), parameter, public fg_yellow = CODE_START//FG//YELLOW//CODE_END
character(len= *), parameter, public fg_white = CODE_START//FG//WHITE//CODE_END
character(len= *), parameter, public fg_ebony = CODE_START//FG//BLACK//CODE_END
character(len= *), parameter, public fg_black = CODE_START//FG//BLACK//CODE_END
character(len= *), parameter, public fg_default = CODE_START//FG//DEFAULT//CODE_END
character(len= *), parameter, public bg_red = CODE_START//BG//RED//CODE_END
character(len= *), parameter, public bg_cyan = CODE_START//BG//CYAN//CODE_END
character(len= *), parameter, public bg_magenta = CODE_START//BG//MAGENTA//CODE_END
character(len= *), parameter, public bg_blue = CODE_START//BG//BLUE//CODE_END
character(len= *), parameter, public bg_green = CODE_START//BG//GREEN//CODE_END
character(len= *), parameter, public bg_yellow = CODE_START//BG//YELLOW//CODE_END
character(len= *), parameter, public bg_white = CODE_START//BG//WHITE//CODE_END
character(len= *), parameter, public bg_ebony = CODE_START//BG//BLACK//CODE_END
character(len= *), parameter, public bg_black = CODE_START//BG//BLACK//CODE_END
character(len= *), parameter, public bg_default = CODE_START//BG//DEFAULT//CODE_END
character(len= *), parameter, public bold = CODE_START//ON//AT_BOLD//CODE_END
character(len= *), parameter, public italic = CODE_START//ON//AT_ITALIC//CODE_END
character(len= *), parameter, public inverse = CODE_START//ON//AT_INVERSE//CODE_END
character(len= *), parameter, public underline = CODE_START//ON//AT_UNDERLINE//CODE_END
character(len= *), parameter, public unbold = CODE_START//'22'//CODE_END
character(len= *), parameter, public unitalic = CODE_START//OFF//AT_ITALIC//CODE_END
character(len= *), parameter, public uninverse = CODE_START//OFF//AT_INVERSE//CODE_END
character(len= *), parameter, public ununderline = CODE_START//OFF//AT_UNDERLINE//CODE_END
character(len= *), parameter, public reset = CODE_RESET
character(len= *), parameter, public clear = HOME_DISPLAY//CLEAR_DISPLAY
integer, save alert_unit =stdout
logical, save alert_debug =.true.
logical, save alert_warn =.true.
logical, save alert_info =.true.
logical, save alert_error =.true.
logical, save alert_other =.true.
Detailed Description
NAME
M_attr(3f) - [M_attr::INTRO] control text attributes on terminals (LICENSE:MIT)
SYNOPSIS
  use M_attr, only : attr, attr_mode, attr_update
  use M_attr, only : alert ! generate standard messages
DESCRIPTION
M_attr(3f) is a Fortran module that uses common ANSI escape sequences to control terminal text attributes.
 use M_attr
 write(*,*)attr('<red>Red Text!</red> <green>Green Text!</green>')
 end
It is designed to use three simple procedures to
Specify attributes using simple HTML-like syntax
allow the sequences to be suppressed when desired
permit the user program to completely customize the keywords. The user can add, delete and replace the sequences associated with a keyword without changing the code.
One advantage of the approach of using formatting directives which are replaced with in-band escape sequences is that it is easy to turn off when running batch.
Another important capability is that programs can be run in "raw" mode and create a simple text file with the formatting directives in it that can then be read back in by a simple filter program that strips it back to plain text(see app/plain.f90), or displays it to a screen in color(see app/light.f90) or perhaps converts it to another format.
So this approach makes it trivial to read specially-formatted data from a file like a message catalog (perhaps with various versions in different languages) and colorize it or display it as plain text
By making each line self-contained (by default) lines can be filtered by external utilities and still display correctly.
ACCESS
Via git(1):
git clone https://github.com/urbanjost/M_attr.git
cd M_attr/src
# change Makefile if not using one of the listed compilers
make clean; make gfortran    # for gfortran
make clean; make ifort       # for ifort
make clean; make nvfortran   # for nvfortran
This will compile the M_attr module and example programs.
Alternatively, via fpm (see https://github.com/fortran-lang/fpm):
 git clone https://github.com/urbanjost/M_attr.git
or just list it as a dependency in your fpm.toml project file.
 [dependencies]
 M_attr = { git = "https://github.com/urbanjost/M_attr.git" }
LIMITATIONS
o colors are not nestable. o keywords are case-sensitive, o ANSI escape sequences are not universally supported by all terminal emulators; and normally should be suppressed when not going to a tty device. Therefore, you should use M_system::system_istty(3f) or the common Fortran extension ISATTY() to set the default to "plain" instead of "color" when the output file is not a conforming terminal. On basic MSWindows console windows, it is best to use Windows 10+ and/or the Linux mode; you may have to enable ANSI escape sequence mode on MSWindows. It does work as-is with CygWin and MinGW and Putty windows and mintty(1) as tested.
EXAMPLE
Sample program
 program demo_M_attr
 use M_attr, only : attr, attr_mode, attr_update, alert
 implicit none
 character(len=256) :: line
 character(len=*),parameter :: f='( &
  &"   <bo><w><G> GREAT: </G></w>&
  &The new value <Y><b>",f8.4,1x,"</b></Y> is in range"&
  &)'
 real :: value
    write(*,'(a)')&
    &attr('   <r><W><bo> ERROR: </W>red text on a white background</y>')
    value=3.4567
    write(line,fmt=f) value
    write(*,'(a)')attr(trim(line))
    ! write same string as plain text
    write(*,*)
    call attr_mode(manner='plain')
    write(*,'(a)')attr(trim(line))
    call attr_mode(manner='color')
    ! use pre-defined or user defined strings
    write(*,*)
    write(*,'(a)')attr('<ERROR> Woe is nigh.')
    write(*,'(a)')attr('<WARNING> The night is young.')
    write(*,'(a)')attr('<INFO> It is Monday')
    call alert('<ERROR>', 'Woe is nigh.')
    call alert('<WARNING>', 'The night is young.')
    call alert('<INFO>', 'It is Monday')
    ! create a custom mnemonic
    call attr_update('MYERROR',attr(&
    ' <R><e> E<w>-<e>R<w>-<e>R<w>-<e>O<w>-<e>R: </e></R></bo>'&
    ))
    write(*,*)
    write(*,'(a)')attr('<MYERROR> my custom message style')
 end program demo_M_attr
AUTHOR
John S. Urban, 2021
LICENSE
MIT
SEE ALSO
attr(3f), attr_mode(3f), attr_update(3f)
Related information:
terminfo(3c), termlib(3c), tput(1), reset(1), clear(1), console_codes(4), ECMA-48, https://en.wikipedia.org/wiki/ANSI_escape_code
Function/Subroutine Documentation
alert()
subroutine, public m_attr::alert (character(len=*), intent(in), optional type, character(len=*), intent(in), optional message, class(*), intent(in), optional g0, class(*), intent(in), optional g1, class(*), intent(in), optional g2, class(*), intent(in), optional g3, class(*), intent(in), optional g4, class(*), intent(in), optional g5, class(*), intent(in), optional g6, class(*), intent(in), optional g7, class(*), intent(in), optional g8, class(*), intent(in), optional g9, class(*), intent(in), optional ga, class(*), intent(in), optional gb, class(*), intent(in), optional gc, class(*), intent(in), optional gd, class(*), intent(in), optional ge, class(*), intent(in), optional gf, class(*), intent(in), optional gg, class(*), intent(in), optional gh, class(*), intent(in), optional gi, class(*), intent(in), optional gj)
!>
NAME
alert(3f) - [M_attr] print messages using a standard format including time and program name (LICENSE:MIT)
SYNOPSIS
 subroutine alert(message,&
 g0,g1,g2,g3,g4,g5,g6,g7,g8,g9,ga,gb,gc,gd,ge,gf,gg,gh,gi,gj)
    character(len=*),intent(in),optional :: type
    character(len=*),intent(in),optional :: message
    class(*),intent(in),optional :: g0,g1,g2,g3,g4,g5,g6,g7,g8,g9, &
                                  & ga,gb,gc,gd,ge,gf,gg,gh,gi,gj
DESCRIPTION
Display a message prefixed with a timestamp and the name of the calling program when the TYPE is specified as any of 'error','warn', or 'info'.
It also allows the keywords <ARG0>,<TZ>,<YE>,<MO>,<DA>,
,<MI>,<SE>,<MS> to be used in the message (which is passed to ATTR(3f)).
Note that time stamp keywords will only be updated when using ALERT(3f) and will only be displayed in color mode!
OPTIONS
TYPE if present and one of 'warn','message','info', or 'debug' a predefined message is written to stderr of the form
:
:<MI>:<SE>.<MS> : (<ARG0>) : TYPE -> message
MESSAGE the user-supplied message to display via a call to ATTR(3f)
g[0-9a-j] optional values to print after the message. May be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX, or CHARACTER.
if no parameters are supplied the macros are updated but no output is generated.
EXAMPLE
Sample program
 program demo_alert
 use M_attr, only : alert, attr, attr_mode
 implicit none
 real X
  call attr_mode(manner='plain')
  call attr_mode(manner='color')
  call alert("error",&
            "Say you didn't!")
  call alert("warn", &
            "I wouldn't if I were you, Will Robinson.")
  call alert("info", &
            "I fixed that for you, but it was a bad idea.")
  call alert("debug", &
            "Who knows what is happening now?.")
  call alert("???    ",  "not today you don't")
  ! call to just update the macros
  call alert()
  ! conventional call to ATTR(3f) using the ALERT(3f)-defined macros
  write(*,*)attr(&
          '<bo>The year was <g><YE></g>, the month was <g><MO></g>')
  ! optional arguments
  X=211.3
  call alert('error',&
          'allowed range of X is 0 <lt> X <lt> 100, X=<r>',X)
  ! up to twenty values are allowed of intrinsic type
  call alert('info','values are<g>',10,234.567,&
          cmplx(11.0,22.0),123.456d0,'</g>today')
 end program demo_alert
Results:
00:38:30: (prg) : error -> Say you didn't! 00:38:30: (prg) : warning -> I wouldn't if I were you, ... Will Robinson. 00:38:30: (prg) : info -> I fixed that for you, ... but it was a bad idea. 00:38:30: (prg) : debug -> Who knows what is happening now?. ... 00:38:30: (prg) : ??? -> not today you don't 00:38:30: (prg) : error -> allowed range of X is 0 X 100, ... X= 211.300003 00:38:30: (prg) : info -> values are 10 234.567001 ... (11.0000000,22.0000000) ... 123.45600000000000 today
AUTHOR
John S. Urban, 2021
LICENSE
MIT
References alert_debug, alert_error, alert_info, alert_other, alert_unit, alert_warn, attr_update(), and values.
attr_matrix()
character(len=:) function, dimension(:), allocatable, private m_attr::attr_matrix (character(len=*), dimension(:), intent(in) strings, logical, intent(in), optional reset, integer, intent(in), optional chars) private
References kludge_bug(), and reset.
attr_mode()
subroutine, public m_attr::attr_mode (character(len=*), intent(in) manner)
!>
NAME
attr_mode(3f) - [M_attr] select processing mode for output from attr(3f) (LICENSE:MIT)
SYNOPSIS
 subroutine attr_mode(manner)
    character(len=*),intent(in) :: manner
DESCRIPTION
Turn off the generation of strings associated with the HTML keywords in the string generated by the attr(3f) function, or display the text in raw mode as it was passed to attr(3f) or return to ANSI escape control sequence generation.
OPTIONS
MANNER The current manners or modes supported via the attr_mode(3f) procedure are
plain suppress the output associated with keywords color(default) commonly supported escape sequences raw echo the input to attr(3f) as its output reload restore original keyword meanings deleted or replaced by calls to attr_update(3f).
EXAMPLE
Sample program
 program demo_attr_mode
 use M_attr, only : attr, attr_mode
 implicit none
 character(len=:),allocatable :: lines(:)
 character(len=:),allocatable :: outlines(:)
 integer :: i
    lines=[character(len=110):: &
    &'<M><y>',&
    &'<M><y>  Suffice it to say that black and white are also colors',&
    &'<M><y>  for their simultaneous contrast is as striking as that ',&
    &'<M><y>  of green and red, for instance. &
    & --- <y><bo>Vincent van Gogh</bo></y>',&
    &' ']
    outlines=attr(lines,chars=57)
    write(*,'(a)')(trim(outlines(i)),i=1,size(outlines))
    call attr_mode(manner='plain') ! write as plain text
    write(*,'(a)')attr(lines)
    call attr_mode(manner='raw')   ! write as-is
    write(*,'(a)')attr(lines)
    call attr_mode(manner='ansi')  ! return to default mode
 end program demo_attr_mode
AUTHOR
John S. Urban, 2021
LICENSE
MIT
References keywords, mode, mono_values, values, and vt102().
attr_scalar()
character(len=:) function, allocatable, private m_attr::attr_scalar (character(len=*), intent(in) string, logical, intent(in), optional reset) private
NAME
attr(3f) - [M_attr] substitute escape sequences for HTML-like syntax in strings (LICENSE:MIT)
SYNOPSIS
  function attr(string,reset) result (expanded)
    ! scalar
    character(len=*),intent(in)  :: string
    logical,intent(in),optional  :: reset
    character(len=:),allocatable :: expanded
    ! or array
    character(len=*),intent(in)  :: string(:)
    logical,intent(in),optional  :: reset
    character(len=:),allocatable :: expanded(:)
    integer,intent(in),optional  :: chars
DESCRIPTION
Use HTML-like syntax to add attributes to terminal output such as color on devices that recognize ANSI escape sequences.
OPTIONS
string input string of form
            "<attribute_name>string</attribute_name> ...".
           where the current attributes are color names,
           bold, italic, underline, ...
reset By default, a sequence to clear all text attributes is sent at the end of each returned line if an escape character appears in the output string. This can be turned off by setting RESET to .false. .
Note if turning off the reset attributes may be continued across lines, but if each line is not self-contained attributes may not display properly when filtered with commands such as grep(1).
chars For arrays, a reset will be placed after the Nth displayable column count in order to make it easier to generate consistent right borders for non-default background colors for a text block.
KEYWORDS
primary default keywords
colors: r, red, R, RED g, green, G, GREEN b, blue, B, BLUE m, magenta, M, MAGENTA c, cyan, C, CYAN y, yellow, Y, YELLOW e, ebony, E, EBONY w, white, W, WHITE
attributes: it, italic bo, bold un, underline
basic control characters: nul bel (0x07, ^G) beeps; bs (0x08, ^H) backspaces one column (but not past the beginning of the line); ht (0x09, ^I) goes to the next tab stop or to the end of the line if there is no earlier tab stop; lf (0x0A, ^J), vt (0x0B, ^K) ff (0x0C, ^L) all give a linefeed, and if LF/NL (new-line mode) is set also a carriage return cr (0x0D, ^M) gives a carriage return; so (0x0E, ^N) activates the G1 character set; si (0x0F, ^O) activates the G0 character set; can (0x18, ^X) and SUB (0x1A, ^Z) interrupt escape sequences; sub esc (0x1B, ^[) starts an escape sequence; del (0x7F) is ignored;
other: clear default reset gt lt save,DECSC Save current state (cursor coordinates, attributes, character sets pointed at by G0, G1). restore,DECRC Restore state most recently saved by ESC 7. CSI "Control Sequence Introducer"(0x9B) is equivalent to "ESC [".
dual-value (one for color, one for mono):
write(*,*)attr('<ERROR>an error message') write(*,*)attr('<WARNING>a warning message') write(*,*)attr('<INFO>an informational message')
By default, if the color mnemonics (ie. the keywords) are uppercase they change the background color. If lowercase, the foreground color. When preceded by a "/" character the attribute is returned to the default.
The "default" keyword is typically used explicitly when reset=.false, and sets all text attributes to their initial defaults.
LIMITATIONS
o colors are not nestable, keywords are case-sensitive, o not all terminals obey the sequences. On Windows, it is best if you use Windows 10+ and/or the Linux mode; although it has worked with all CygWin and MinGW and Putty windows and mintty. o you should use "<gt>" and "<lt>" instead of ">" and "<" in a string processed by attr(3f) instead of in any plain text output so that the raw mode will create correct input for the attr(3f) function if read back in.
EXAMPLE
Sample program
 program demo_attr
 use M_attr, only : attr, attr_mode, attr_update
    call printstuff('defaults')
    call attr_mode(manner='plain')
    call printstuff('plain:')
    call printstuff('raw')
    call attr_mode(manner='color')
    call printstuff('')
    write(*,'(a)') attr('TEST ADDING A CUSTOM SEQUENCE:')
    call attr_update('blink',char(27)//'[5m')
    call attr_update('/blink',char(27)//'[25m')
    write(*,'(a)') attr('<blink>Items for Friday</blink>')
 contains
 subroutine printstuff(label)
 character(len=*),intent(in)  :: label
 character(len=:),allocatable :: array(:)
   call attr_mode(manner=label)
   array=[character(len=60) ::    &
    'TEST MANNER='//label,                      &
    '<r>RED</r>,<g>GREEN</g>,<b>BLUE</b>',      &
    '<c>CYAN</c>,<m>MAGENTA</g>,<y>YELLOW</y>', &
    '<w>WHITE</w> and <e>EBONY</e>']
   write(*,'(a)') attr(array)
   write(*,'(a)') attr('Adding <bo>bold</bo>')
   write(*,'(a)') attr('<bo><r>RED</r>,<g>GREEN</g>,<b>BLUE</b></bo>')
   write(*,'(a)') attr('<bo><c>CYAN</c>,<m>MAGENTA</g>,<y>YELLOW</y></bo>')
   write(*,'(a)') attr('<bo><w>WHITE</w> and <e>EBONY</e></bo>')
   write(*,'(a)') attr('Adding <ul>underline</ul>')
   write(*,'(a)') attr(&
    &'<bo><ul><r>RED</r>,<g>GREEN</g>,<b>BLUE</b></ul></bo>')
   write(*,'(a)') attr(&
    &'<bo><ul><c>CYAN</c>,<m>MAGENTA</g>,<y>YELLOW</y></ul></bo>')
   write(*,'(a)') attr('<bo><ul><w>WHITE</w> and <e>EBONY</e></ul></bo>')
   write(*,'(a)') attr('Adding <ul>italic</ul>')
   write(*,'(a)') attr(&
    &'<bo><ul><it><r>RED</r>,<g>GREEN</g>,<b>BLUE</b></it></ul></bo>')
   write(*,'(a)') attr(&
    &'<bo><ul><it><c>CYAN</c>,<m>MAGENTA</g>,<y>YELLOW</it></y></ul></bo>')
   write(*,'(a)') attr('<bo><ul><it><w>WHITE</w> and <e>EBONY</e></ul></bo>')
   write(*,'(a)') attr('Adding <in>inverse</in>')
   write(*,'(a)') attr('<in><bo><ul><it><r>RED</r>,<g>GREEN</g>,&
    &<b>BLUE</b></it></ul></bo></in>')
   write(*,'(a)') attr('<in><bo><ul><it><c>CYAN</c>,<m>MAGENTA</g>,&
    &<y>YELLOW</it></y></ul></bo></in>')
   write(*,'(a)') attr(&
    &'<in><bo><ul><it><w>WHITE</w> and <e>EBONY</e></ul></bo></in>')
 end subroutine printstuff
 end program demo_attr
AUTHOR
John S. Urban, 2021
LICENSE
MIT
SEE ALSO
attr_mode(3f), attr_update(3f)
References code_reset, esc, get(), keywords, locate(), mode, reset, and vt102().
attr_scalar_width()
character(len=:) function, allocatable, private m_attr::attr_scalar_width (character(len=*), intent(in) string, logical, intent(in), optional reset, integer, intent(in) chars) private
References attr_matrix(), and reset.
attr_update()
subroutine, public m_attr::attr_update (character(len=*), intent(in) key, character(len=*), intent(in), optional valin, character(len=*), intent(in), optional mono_valin)
!>
NAME
attr_update(3f) - [M_attr] update internal dictionary given keyword and value (LICENSE:MIT)
SYNOPSIS
subroutine attr_update(key,val)
 character(len=*),intent(in)           :: key
 character(len=*),intent(in),optional  :: val
 character(len=*),intent(in),optional  :: mono_val
DESCRIPTION
Update internal dictionary in M_attr(3fm) module.
OPTIONS
key name of keyword to add, replace, or delete from dictionary val if present add or replace value associated with keyword. If not present remove keyword entry from dictionary. mono_val if present add or replace second value associated with keyword used for plain text mode. Must only be specified if VAL is also specified.
KEYWORDS
The following keywords are defined by default
colors:
r,red c,cyan w,white g,green m,magenta e,ebony b,blue y,yellow
If the color keywords are capitalized they control the text background instead of the text color.
attributes:
ul,underline it,italics (often produces inverse colors on many devices
EXAMPLE
Sample program
  program demo_update
  use M_attr, only : attr, attr_update
     write(*,'(a)') attr('<clear>TEST CUSTOMIZATIONS:')
     ! add custom keywords
     call attr_update('blink',char(27)//'[5m')
     call attr_update('/blink',char(27)//'[25m')
     write(*,*)
     write(*,'(a)') attr('<blink>Items for Friday</blink>')
     call attr_update('ouch',attr( &
     ' <R><bo><w>BIG mistake!</R></w> '))
     write(*,*)
     write(*,'(a)') attr('<ouch> Did not see that coming.')
     write(*,*)
     write(*,'(a)') attr( &
     'ORIGINALLY: <r>Apple</r>, <b>Sky</b>, <g>Grass</g>')
     ! delete
     call attr_update('r')
     call attr_update('/r')
     ! replace (or create)
     call attr_update('b','<<<<')
     call attr_update('/b','>>>>')
     write(*,*)
     write(*,'(a)') attr( &
     'CUSTOMIZED: <r>Apple</r>, <b>Sky</b>, <g>Grass</g>')
  end program demo_update
AUTHOR
John S. Urban, 2021
LICENSE
MIT
References insert(), keywords, locate(), mode, mono_values, remove(), replace(), values, and vt102().
get()
character(len=:) function, allocatable, private m_attr::get (character(len=*), intent(in) key) private
References keywords, locate(), mode, mono_values, and values.
insert()
subroutine, private m_attr::insert (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(in) place) private
kludge_bug()
subroutine m_attr::kludge_bug (character(len=*), dimension(:), intent(in) strings, logical, intent(in), optional reset, integer, intent(in), optional chars, character(len=:), dimension(:), allocatable expanded) private
References attr_scalar(), mode, and vt102().
locate()
subroutine, private m_attr::locate (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(out) place, integer, intent(out), optional ier, character(len=*), intent(out), optional errmsg) private
msg_one()
character(len=:) function, allocatable m_attr::msg_one (class(*), dimension(:), intent(in) generic0, class(*), dimension(:), intent(in), optional generic1, class(*), dimension(:), intent(in), optional generic2, class(*), dimension(:), intent(in), optional generic3, class(*), dimension(:), intent(in), optional generic4, class(*), dimension(:), intent(in), optional generic5, class(*), dimension(:), intent(in), optional generic6, class(*), dimension(:), intent(in), optional generic7, class(*), dimension(:), intent(in), optional generic8, class(*), dimension(:), intent(in), optional generic9, class(*), dimension(:), intent(in), optional generica, class(*), dimension(:), intent(in), optional genericb, class(*), dimension(:), intent(in), optional genericc, class(*), dimension(:), intent(in), optional genericd, class(*), dimension(:), intent(in), optional generice, class(*), dimension(:), intent(in), optional genericf, class(*), dimension(:), intent(in), optional genericg, class(*), dimension(:), intent(in), optional generich, class(*), dimension(:), intent(in), optional generici, class(*), dimension(:), intent(in), optional genericj, character(len=*), intent(in), optional sep) private
References print_generic().
msg_scalar()
character(len=:) function, allocatable m_attr::msg_scalar (class(*), intent(in), optional generic0, class(*), intent(in), optional generic1, class(*), intent(in), optional generic2, class(*), intent(in), optional generic3, class(*), intent(in), optional generic4, class(*), intent(in), optional generic5, class(*), intent(in), optional generic6, class(*), intent(in), optional generic7, class(*), intent(in), optional generic8, class(*), intent(in), optional generic9, class(*), intent(in), optional generica, class(*), intent(in), optional genericb, class(*), intent(in), optional genericc, class(*), intent(in), optional genericd, class(*), intent(in), optional generice, class(*), intent(in), optional genericf, class(*), intent(in), optional genericg, class(*), intent(in), optional generich, class(*), intent(in), optional generici, class(*), intent(in), optional genericj, character(len=*), intent(in), optional sep) private
NAME
str(3f) - [M_attr] converts any standard scalar type to a string (LICENSE:PD)
SYNOPSIS
Syntax:
  function str(g0,g1,g2,g3,g4,g5,g6,g7,g8,g9,&
  & ga,gb,gc,gd,ge,gf,gg,gh,gi,gj,sep)
  class(*),intent(in),optional  :: g0,g1,g2,g3,g4,g5,g6,g7,g8,g9
  class(*),intent(in),optional  :: ga,gb,gc,gd,ge,gf,gg,gh,gi,gj
  character(len=*),intent(in),optional :: sep
  character,len=(:),allocatable :: str
DESCRIPTION
str(3f) builds a space-separated string from up to twenty scalar values.
OPTIONS
g[0-9a-j] optional value to print the value of after the message. May be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX, or CHARACTER.
Optionally, all the generic values can be single-dimensioned arrays. Currently, mixing scalar arguments and array arguments is not supported.
sep separator string used between values. Defaults to a space.
RETURNS
str description to print
EXAMPLES
Sample program:
program demo_msg use M_attr, only : alert end program demo_msg
Output
AUTHOR
John S. Urban
LICENSE
Public Domain
References print_generic().
remove()
subroutine, private m_attr::remove (character(len=:), dimension(:), allocatable list, integer, intent(in) place) private
replace()
subroutine, private m_attr::replace (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(in) place) private
vt102()
subroutine, private m_attr::vt102 private
References attr_update(), bel, bell, bg_blue, bg_cyan, bg_default, bg_ebony, bg_green, bg_magenta, bg_red, bg_white, bg_yellow, bold, bs, can, clear, cr, del, esc, ff, fg_blue, fg_cyan, fg_default, fg_ebony, fg_green, fg_magenta, fg_red, fg_white, fg_yellow, ht, inverse, italic, lf, nul, reset, si, so, sub, unbold, underline, uninverse, unitalic, ununderline, vt, and wipe_dictionary().
wipe_dictionary()
subroutine, private m_attr::wipe_dictionary private
References keywords, mono_values, and values.
Variable Documentation
alert_debug
logical, save m_attr::alert_debug =.true. private
alert_error
logical, save m_attr::alert_error =.true. private
alert_info
logical, save m_attr::alert_info =.true. private
alert_other
logical, save m_attr::alert_other =.true. private
alert_unit
integer, save m_attr::alert_unit =stdout private
alert_warn
logical, save m_attr::alert_warn =.true. private
at_bold
character(len=*), parameter m_attr::at_bold ='1' private
at_inverse
character(len=*), parameter m_attr::at_inverse ='7' private
at_italic
character(len=*), parameter m_attr::at_italic ='3' private
at_underline
character(len=*), parameter m_attr::at_underline ='4' private
bel
character(len=*), parameter m_attr::bel =achar(7) private
bell
character(len=*), parameter m_attr::bell =achar(7) private
bg
character(len=*), parameter m_attr::bg ='4' private
bg_black
character(len=*), parameter, public m_attr::bg_black = CODE_START//BG//BLACK//CODE_END
bg_blue
character(len=*), parameter, public m_attr::bg_blue = CODE_START//BG//BLUE//CODE_END
bg_cyan
character(len=*), parameter, public m_attr::bg_cyan = CODE_START//BG//CYAN//CODE_END
bg_default
character(len=*), parameter, public m_attr::bg_default = CODE_START//BG//DEFAULT//CODE_END
bg_ebony
character(len=*), parameter, public m_attr::bg_ebony = CODE_START//BG//BLACK//CODE_END
bg_green
character(len=*), parameter, public m_attr::bg_green = CODE_START//BG//GREEN//CODE_END
bg_intense
character(len=*), parameter m_attr::bg_intense ='10' private
bg_magenta
character(len=*), parameter, public m_attr::bg_magenta = CODE_START//BG//MAGENTA//CODE_END
bg_red
character(len=*), parameter, public m_attr::bg_red = CODE_START//BG//RED//CODE_END
bg_white
character(len=*), parameter, public m_attr::bg_white = CODE_START//BG//WHITE//CODE_END
bg_yellow
character(len=*), parameter, public m_attr::bg_yellow = CODE_START//BG//YELLOW//CODE_END
black
character(len=*), parameter m_attr::black ='0' private
blue
character(len=*), parameter m_attr::blue ='4' private
bold
character(len=*), parameter, public m_attr::bold = CODE_START//ON//AT_BOLD//CODE_END
bs
character(len=*), parameter m_attr::bs =achar(8) private
can
character(len=*), parameter m_attr::can =achar(24) private
clear
character(len=*), parameter, public m_attr::clear = HOME_DISPLAY//CLEAR_DISPLAY
clear_display
character(len=*), parameter m_attr::clear_display =CODE_START//'2J' private
code_end
character(len=*), parameter m_attr::code_end ='m' private
code_reset
character(len=*), parameter m_attr::code_reset =CODE_START//'0'//CODE_END private
code_start
character(len=*), parameter m_attr::code_start =esc//'[' private
cr
character(len=*), parameter m_attr::cr =achar(13) private
cyan
character(len=*), parameter m_attr::cyan ='6' private
default
character(len=*), parameter m_attr::default ='9' private
del
character(len=*), parameter m_attr::del =achar(127) private
esc
character(len=*), parameter m_attr::esc =achar(27) private
ff
character(len=*), parameter m_attr::ff =achar(12) private
fg
character(len=*), parameter m_attr::fg ='3' private
fg_black
character(len=*), parameter, public m_attr::fg_black = CODE_START//FG//BLACK//CODE_END
fg_blue
character(len=*), parameter, public m_attr::fg_blue = CODE_START//FG//BLUE//CODE_END
fg_cyan
character(len=*), parameter, public m_attr::fg_cyan = CODE_START//FG//CYAN//CODE_END
fg_default
character(len=*), parameter, public m_attr::fg_default = CODE_START//FG//DEFAULT//CODE_END
fg_ebony
character(len=*), parameter, public m_attr::fg_ebony = CODE_START//FG//BLACK//CODE_END
fg_green
character(len=*), parameter, public m_attr::fg_green = CODE_START//FG//GREEN//CODE_END
fg_intense
character(len=*), parameter m_attr::fg_intense ='9' private
fg_magenta
character(len=*), parameter, public m_attr::fg_magenta = CODE_START//FG//MAGENTA//CODE_END
fg_red
character(len=*), parameter, public m_attr::fg_red = CODE_START//FG//RED//CODE_END
fg_white
character(len=*), parameter, public m_attr::fg_white = CODE_START//FG//WHITE//CODE_END
fg_yellow
character(len=*), parameter, public m_attr::fg_yellow = CODE_START//FG//YELLOW//CODE_END
green
character(len=*), parameter m_attr::green ='2' private
home_display
character(len=*), parameter m_attr::home_display =CODE_START//'H' private
ht
character(len=*), parameter m_attr::ht =achar(9) private
inverse
character(len=*), parameter, public m_attr::inverse = CODE_START//ON//AT_INVERSE//CODE_END
italic
character(len=*), parameter, public m_attr::italic = CODE_START//ON//AT_ITALIC//CODE_END
keywords
character(len=:), dimension(:), allocatable, save m_attr::keywords private
lf
character(len=*), parameter m_attr::lf =achar(10) private
magenta
character(len=*), parameter m_attr::magenta ='5' private
mode
character(len=:), allocatable, save m_attr::mode private
mono_values
character(len=:), dimension(:), allocatable, save m_attr::mono_values private
nl
character(len=*), parameter m_attr::nl =new_line('a') private
nul
character(len=*), parameter m_attr::nul =achar(0) private
off
character(len=*), parameter m_attr::off ='2' private
on
character(len=*), parameter m_attr::on ='' private
red
character(len=*), parameter m_attr::red ='1' private
reset
character(len=*), parameter, public m_attr::reset = CODE_RESET
si
character(len=*), parameter m_attr::si =achar(15) private
so
character(len=*), parameter m_attr::so =achar(14) private
sub
character(len=*), parameter m_attr::sub =achar(26) private
unbold
character(len=*), parameter, public m_attr::unbold = CODE_START//'22'//CODE_END
underline
character(len=*), parameter, public m_attr::underline = CODE_START//ON//AT_UNDERLINE//CODE_END
uninverse
character(len=*), parameter, public m_attr::uninverse = CODE_START//OFF//AT_INVERSE//CODE_END
unitalic
character(len=*), parameter, public m_attr::unitalic = CODE_START//OFF//AT_ITALIC//CODE_END
ununderline
character(len=*), parameter, public m_attr::ununderline = CODE_START//OFF//AT_UNDERLINE//CODE_END
values
character(len=:), dimension(:), allocatable, save m_attr::values private
vt
character(len=*), parameter m_attr::vt =achar(11) private
white
character(len=*), parameter m_attr::white ='7' private
yellow
character(len=*), parameter m_attr::yellow ='3' private