name: macos with gfortran

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13 ]
        include:
        - os: macos-13
          gcc_v: 14
    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}
      TZ: UTC+04:00

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install fpm
      run: |
           ls /usr/local/bin/gfortran*
           ln -f -s /usr/local/bin/gfortran-${GCC_V} /usr/local/bin/gfortran
           echo $PATH
           pwd
           uname -a
           wget https://raw.githubusercontent.com/lockstockandbarrel/mars/main/bootstrap/fpm.F90
           mkdir -p /Users/runner/bin tmp
           ulimit -c unlimited -d unlimited -f unlimited -m unlimited -t unlimited -v unlimited
           gfortran fpm.F90 -Jtmp -Itmp -o /Users/runner/bin/fpm
           rm -f tmp/*.mod
           ls -l

    - name: Display environment
      run: |
        echo $PATH
        pwd
        uname -a
        ulimit -a
        echo "end" > foo.f90
        gfortran -cpp -E -dM foo.f90
        gfortran --version
        fpm --version
        ulimit -a

    - name: tests MacOS (release)
      run: |
          ulimit -c unlimited -d unlimited -f unlimited -m unlimited -t unlimited -v unlimited
          exec 2>&1
          set -x
          ulimit -S -t 1800
          timeout 0.5h fpm test --profile debug --verbose

    - name: tests MacOS (debug)
      run: |
          ulimit -c unlimited -d unlimited -f unlimited -m unlimited -t unlimited -v unlimited
          exec 2>&1
          set -x
          ulimit -S -t 1800
          fpm test --profile debug --verbose

    - name: cleanup MacOS
      run: ls -ltras
##########################################################
